# Generated by Django 3.2.6 on 2021-10-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211023_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='image',
            field=models.ImageField(upload_to='ReciepeImages'),
        ),
    ]
